# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Medina Blog
tagline:          ''
description:      'A Software Engineer Student'
url:              
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

profile-img:
  url: '' # url completa (http o https)
  img-source: '' # Por defecto /assets/img/profile.jpg 

collections:
  blog:
    output: true
    permalink: /:collection/:title/

author:
  name: 'Medina'
  url:  ''
  github-user: 'NigelMedina28'         
  facebook-user: 'Nigelo09'
  instagram-user: 'nigelmedina9' 

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
